spring.datasource.url=jdbc:mysql://localhost:3306/projet_pfe?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Brevo SMTP configuration
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a41e63001@smtp-brevo.com
spring.mail.password=ZW7GM1PLD8Cd3Sa5
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

brevo.api.key=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

server.error.include-message=always

# Allow larger file uploads
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

anthropic.api.key=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

# JWT
jwt.secret=MonSuperSecretPourPFEQuiDoitEtreAssezLong123!
jwt.expiration=28800000

#app.base-url=https://fragrant-collapse-cuddly.ngrok-free.dev

cloudinary.cloud-name=dkddgnakd
cloudinary.api-key=786662951988559
cloudinary.api-secret=tA831TIYDL3Y1_4wIYT4Irr6Br8